### ISSUE TITLE
Request for is_activated function in rpc library

### ISSUE THREAD

**Issue by msbreton** [open-amt-cloud-toolkit/rpc-go#135]
We have a flow,, and will have more in the future, that we don't want to call if the device hasn't been successfully activated.  Today we are calling rpc amtinfo and parsing the output for a particular string to determine if the device is activated.  It would be optimal if we could call a specific function that returned a status code (activated or not).

**Comment by bwendlandt-intel** [comment]
Hi @msbreton ,

This is possible today with RPC.

The following command will return a JSON response with only the controlMode eliminating the need for any string parsing.
```
rpc amtinfo -mode -json
```

Example return output:
```
{
  "controlMode": "pre-provisioning state"
}
```

Other possible return controlModes:
```
"activated in admin control mode"
"activated in client control mode"
```

You can find all possible `amtinfo` flags in the [RPC CLI Documentation](https://open-amt-cloud-toolkit.github.io/docs/2.10/Reference/RPC/commandsRPC/#amtinfo)

Please let us know if this existing capability meets what you are looking for. Thanks!

**Comment by bwendlandt-intel** [comment]
Did the team reach a decision on if this feature will work? Or do we need to explore some other options?

**Comment by msbreton** [comment]
My apologies for the delay.  Seems we had some issue parsing the output as  you suggested, possibly because we are writing in C# but calling Golang rpc.  We thought this might be an easier way to resolve that.  Upon further discussion, we will need to parse additional amtinfo output in the future and thus must resolve our parsing issue.  Closing this request.  Thank you.
