### ISSUE TITLE
rpc deactivation wipe out the custom CA hashes that were added via MEBx

### ISSUE THREAD

**Issue by gfrankliu** [open-amt-cloud-toolkit/rpc-go#140]
We have some test internal CA hashes that we added manually via MEBx.
When testing rpc, we found that during deactivation, those CA hashes got deleted though they were NOT added by rpc activation.

Can we make rpc not to do that? and maybe add an option for those people who really wants to do that (very unlikely, but possible).

Long term, AMT firmware should be updated to disable such operations. The Host OS / app (like rpc) should NOT be able to send a command to AMT to wipe out those CA hashes. They should only be added/deleted via the MEBx/USB.

**Comment by bwendlandt-intel** [comment]
Hi Frank,

To provide some additional information here maybe:

#### Background Info
Currently, during a `full unprovision`, AMT will remove any added CA hashes.  The team has started a discussion with the firmware side of the house to see if this can be updated in the future.  Although, this would most likely only apply to new release versions of AMT (think AMT 18+), **if implemented**.  At this point in time, There is no guarantee that I can provide as talks are early.

The team can look into adding `partial unprovision` to RPC as a new feature.  It seems we did some pathfinding on this previously and found a number of technical challenges for implementing this feature that have some impacts to device connectivity and reprovisioning.

Losing CA hashes is typically not an issue in production as devices are normally only unprovisioned when decommissioned.  If changes to configuration are needed, a device can run `activation` or `maintenance` commands to reconfigure it.

#### Workaround
Of course, during testing or evaluation, losing hashes can be irksome as you activate/deactivate devices.  One option is that some AMT solutions support Device Migration.  This includes both Open AMT as well as Intel EMA.  By running an RPC `activate` command on an already activated device, you can reconfigure and [migrate this device to Open AMT from another management service](https://open-amt-cloud-toolkit.github.io/docs/2.11/Reference/RPC/buildRPC_Manual/?h=device#transition-activated-device). Or vice versa from Open AMT to EMA using their tools.

<br>

We have added `partial unprovision` into our backlog, but hopefully this provides some insight into where we are today.
