### ISSUE TITLE
Feature Request: Always enable wifiPort if present

### ISSUE THREAD

**Issue by matt-primrose** [open-amt-cloud-toolkit/rpc-go#160]
**Describe the bug** 🪲
Customer is reporting that if they don't have a wifi profile specified in the AMT Profile, then RPS is not enabling WiFIPort or LocalProfileSync.  Request is to always enable WiFi Port as well as LocalProfileSync.  

This impacts them when they later attempt to configure a wifi profile locally using RPC

**To Reproduce** 🪜
1. create AMT profile without wifi profile
2. Activate device
3. Check wifi port status and see it is disabled

**Expected behavior**
Desired behavior would be to always enable the WiFi Port on AMT when activating a device that has an AMT WiFi adapter

**Comment by madhavilosetty-intel** [comment]
Must provide a Wi-Fi profile to enable a Wi-Fi port on AMT.
