### ISSUE TITLE
Feature Request: New flag to pass in custom unique UUID

### ISSUE THREAD

**Issue by bwendlandt-intel** [open-amt-cloud-toolkit/rpc-go#163]
Currently, some AMT devices could have duplicate UUIDs due to OEM errors.  This causes one device to overwrite the other within the database and secret store leading to issues when managing devices since the UUID is the sole primary key right now.

It would be good to have a new flag, like`-id`, when running RPC-Go that will allow the passing of a custom id string in place of using the UUID.  This would allow the ability to solve the duplication problem remotely by sidestepping UUID rather than having to use manual touch OEM solutions to fix the UUIDs themselves.

This would not work for CIRA-based connected devices.  Exclusively solves the problem for enterprise, non-CIRA type environments.

Tasks:
- [x] Add -uuid input flag to RPC-Go
- [x] uuid provided must match standard uuid format
- [x] RPC-Go replaces AMT uuid when sending device data to RPS
- [x] Add warning message to RPC-Go that using -uuid flag to override AMT uuid will prevent AMT device from connecting to MPS
- [ ] Add documentation to RPC-Go page for the -uuid flag and the impact of using this feature. Also document new error code

**Comment by matt-primrose** [comment]
- [ ] Update the database script to make a composite key of UUID and Friendly name
- [ ] Add a device using the REST API
- [ ] Discuss the observations with team and finalize the next steps

**Comment by matt-primrose** [comment]
Previous implementation proposal won't work.  Updated original post with updated tasks for implementation
