### ISSUE TITLE
Invalid comment lines on Dockerfile

### ISSUE THREAD

**Issue by lobando** [open-amt-cloud-toolkit/rpc-go#18]
I believe the header with comments are invalid for a Dockerfile

https://github.com/open-amt-cloud-toolkit/rpc-go/blob/255f51fba61bf1086bbf24f27a2316b570a3652a/Dockerfile#L1

See

https://docs.docker.com/engine/reference/builder/#format

**Comment by SvenDowideit** [comment]
https://github.com/open-amt-cloud-toolkit/rpc-go/pull/20
