### ISSUE TITLE
amtinfo is displaying the hostname in the 'Hostname (OS)' and 'DNS Suffix (OS)' on an Ubuntu device

### ISSUE THREAD

**Issue by Walt-Intel** [open-amt-cloud-toolkit/rpc-go#227]
amt@amt11-8-93:~/rpc-go$ sudo ./rpc version
RPC
Version 2.15.0
Protocol 4.0.0

amt@amt11-8-93:~/rpc-go$ sudo ./rpc amtinfo 
Version			: 11.8.93
Build Number		: 4323
SKU		  	        : 16392
Features		        : AMT Pro Corporate 
UUID			: 04bcf4e9-51e4-4a45-b64c-54b2038bea9a
Control Mode		: activated in admin control mode
DNS Suffix		: vprodemo.com
DNS Suffix (OS)	: amt11-8-93
Hostname (OS)		: amt11-8-93
RAS Network      	: outside enterprise
RAS Remote Status	: connecting
RAS Trigger      	: periodic
RAS MPS Hostname 	: 192.168.8.50

![image](https://github.com/open-amt-cloud-toolkit/rpc-go/assets/45042147/14b3fc6b-6a4e-4b04-a2ac-b096d304610e)

**Comment by bwendlandt-intel** [comment]
Closing as Duplicate, see Issue #189
