### ISSUE TITLE
Gosh it would be excellent if rpc could tell the user that they don't have an AMT compatible network device

### ISSUE THREAD

**Issue by SvenDowideit** [open-amt-cloud-toolkit/rpc-go#28]
cos I have this stupendously expensive new Thinkpad P1 gen4 with an i9, that has a great big "Intel CORE vPRO" sticker on it.

but after much to-ing and fro-ing, we're pretty sure that because it doesn't have a built in ethernet, and my Dock is an older USB-C Dock, that this is the reason it won't activate.

There are a bunch of things that also lead the AMT expert to parts of this conclusion, but hopefully, its possible to detect that the ethernet interfaces are not connected to the AMT system directly.

**Comment by matt-primrose** [comment]
I think this gets solved with two different changes:
1. We can provide an indication if the AMT NIC has a connection or not based on information we get from the OS
2. Need to sync with ME FW team to determine when USB-C support for AMT was added so that wired NICs on docks support AMT communication

**Comment by SvenDowideit** [comment]
I've bought the new lenovo thunderbolt 4 dock, and will hopefully test that and report back some time this month
