### ISSUE TITLE
"Exception 0xc0000005 0x0 0x7fff40104e30 0x7ff9eab5b057 PC=0x7ff9eab5b057  runtime: unknown pc 0x7ff9eab5b057" while running the rpc activation command

### ISSUE THREAD

**Issue by BhargaviChintanippu** [open-amt-cloud-toolkit/rpc-go#34]
Hi Team, 

Followed the [Build & Run RPC](https://open-amt-cloud-toolkit.github.io/docs/2.1/GetStarted/buildRPC/) link and built the RPC on windows but facing "Exception 0xc0000005 0x0 0x7fff40104e30 0x7ff9eab5b057 PC=0x7ff9eab5b057  runtime: unknown pc 0x7ff9eab5b057" issue while running the rpc activation command and not able to provision the device.

**Client Edge Device Details**:
   OS : Windows 10
   GO version : go1.17.6 windows/amd64
   GCC version : 10.3.0 (tdm64-1)

**go build output and rpc version** : 
![rpc](https://user-images.githubusercontent.com/45841187/149954042-d2a418a9-989b-412b-a3cd-3d8c312f9592.png)

command used: .\rpc.exe activate -u wss://serveripaddress/activate -n --profile ccmprofile

Attached the error log for reference.
[rpc-go-issue-log.txt](https://github.com/open-amt-cloud-toolkit/rpc-go/files/7889914/rpc-go-issue-log.txt)

Request your help in resolving this issue.

Thanks & Regards,
Bhargavi

**Comment by rsdmike** [comment]
Hey There, what AMT version do you have?

**Comment by BhargaviChintanippu** [comment]
@rsdmike , I am using AMT Version - 11.8.86
![amtinfo](https://user-images.githubusercontent.com/45841187/150262754-153e07d2-8330-45b4-8234-61b703b607ea.png)

**Comment by BhargaviChintanippu** [comment]
@rsdmike , Could you please provide the steps to resolve this issue?

**Comment by rsdmike** [comment]
Hey there @BhargaviChintanippu , for version AMT 11 and before you might be better off using the C version. That said, I have a workaround. You'll have to make a slight modification in the code. 
1) You'll need to install Visual Studio 2013 Redistributable Pack (https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist) 
2) Update line 9 of lms.go `-lucrtbase` to `-lmsvcr120`
3) Put the msvcr120.dll in the same folder as rpc.exe and then try it. 

That should fix the issue, if it doesn't let us know.

**Comment by BhargaviChintanippu** [comment]
Thanks @rsdmike for the workaround. I will try and let you know the update.

**Comment by BhargaviChintanippu** [comment]
Hi @rsdmike, Tried following the workaround instructions but facing the "**Exception 0xc0000005 0x1 0x24 0x7ff9eb6b3416
PC=0x7ff9eb6b3416 runtime: unknown pc 0x7ff9eb6b3416**" issue. 
1. Installed the Visual Studio 2013 Redistributable Package- version 12.0.40664.0.
2. Updated the line 9 of **commands.go** -lucrtbase to -lmsvcr120 as I didn't find -lucrtbase in lms.go file.
3. Executed the rpc.exe activate command after putting the msvcr120.dll in the same folder, but it didn't work. Not able to provision the device, facing the "runtime: unknown pc 0x7ff9eb6b3416" issue.

Attached the error log for reference.
[rpc-go-error.txt](https://github.com/open-amt-cloud-toolkit/rpc-go/files/7926442/rpc-go-error.txt)

Could you please help in resolving this issue.

Thanks & Regards,
Bhargavi

**Comment by bchint1x** [comment]
Hi Team, Thanks for the inputs..  I was able to resolve the issue by wiping out the existing OS image and reinstalling Windows. Followed the [Build & Run RPC](https://open-amt-cloud-toolkit.github.io/docs/2.1/GetStarted/buildRPC/) provisioned the device.
![image](https://user-images.githubusercontent.com/90310574/158379094-73f145ee-3b71-42c2-885a-781de97545b5.png)

**Comment by matt-primrose** [comment]
issue resolved.
