### ISSUE TITLE
Root certificates not present in AMT device

### ISSUE THREAD

**Issue by UshitaG** [open-amt-cloud-toolkit/rpc-go#42]
Receiving this error message while activating device.

![MicrosoftTeams-image (15)](https://user-images.githubusercontent.com/39854283/161965737-a563bbc4-23a1-4ff0-99ee-ed585bc5edf6.png)

./rpc --amtinfo cert
returns no certificate hashes

**Comment by matt-primrose** [comment]
This is seen on a Lenovo M80Q

**Comment by matt-primrose** [comment]
Current limit in RPC was set to 23 which accounted for the 0-19 factory default and 20-22 user creatable hashes.  It did not account for the 23-32 additional factory default hashes that could be included.  PR#44 accounts for these additional factory default hashes
