### ISSUE TITLE
RPC Go -local fails to configure ISM devices in Admin Control Mode

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/rpc-go#428]
Running RCP -local -acm on ISM system fails to configure with error activation failed message.

screen shot of failure
![image](https://github.com/open-amt-cloud-toolkit/rpc-go/assets/140858054/a9108a92-21e1-48af-98ce-f8c25d3d3911)

Reproduce steps:

1. Go into MEBx and enter DNS suffix "vprodem.com"
2. Boot to OS and type command in terminal. "rpc.exe activate -local -acm -config ./config.yaml -v"
3. Error shows "activation failed"

Tested platform = HP MP9 ISM with firmware version 11.8.86

Note: RPC local can configure the ISM platform in CCM. It only fails when trying to configure in ACM.

Walmart is seeing this behavior. Corey and I are able to reproduce this failure.

**Comment by mtpham-1** [comment]
Just tested on a vPro Essentials AMT version 16.1.25 and it also fails.

![image](https://github.com/open-amt-cloud-toolkit/rpc-go/assets/140858054/0fbf5889-4431-4d24-ae88-c82d9d307a52)


Note: One thing we notice is it asks for the AMT password when the system is fully unconfigured. Expect that it should not ask for the AMT password.

**Comment by matt-primrose** [comment]
@mtpham-1 the password confirmation is a new feature we added.  Essentially this is setting the password for AMT when we are activating and we want to confirm the password with the user just to prevent a typo.  That being said, I'm assuming you have a password set in your config.yaml file, correct?  If that is the case, then this is a bug with the password confirmation feature where we should be parsing the config file first and see if a password is there before prompting the user for a password.  I'll add this as a separate issue.

**Comment by mtpham-1** [comment]
Hi Matt, 

Yes, there is a admin password in the yaml file. Thanks for logging a bug to check for the password.

So we still have the issue with configuring ISM in ACM.

-Minh

**Comment by matt-primrose** [comment]
Hi @mtpham-1,

I tested on my ISM 16.1 machine, and I was able to activate locally to both CCM and ACM.  I'm assuming we are using the same provisioning certificate (vprodemo.com).  The only difference I can see between our two amtinfo outputs is that you have intel.vprodemo.com for your DNS Suffix and I am using vprodemo.com.  It shouldn't make a difference as RPC-Go isn't performing any certificate checks and is just relying on AMT to validate the certificate.

**Comment by mtpham-1** [comment]
Corey and I tested with the new rpc 2.29.1 version and the systems that were failing before are now able to configure in ACM now. The difference in this version is it doesn't prompt for the AMT password anymore since you put logic in there to not prompt for it if the yaml has a password. For whatever reason, the ACM config failed before when it prompts for the password.  Go ahead and close this case.
