### ISSUE TITLE
Re-enable port 16992/16993

### ISSUE THREAD

**Issue by lschnetl** [open-amt-cloud-toolkit/rpc-go#503]
After migrating a bunch of hosts to OpenAMT we started seeing that their http and https ports closed off. At first, it was ok, but after a while, we couldn't get access to them via the RPS and soon after we were unable to communicate with them at all. Some of them reverted back to a DHCP mode and that blocks us completely from sending IPMI commands from other services like MAAS.

I recently discovered that using the docker image, we can force a connection to the /dev/mei0 port that would allow us to re-establish a connection to the RPS server, if they crash for whatever reason. The only catch being we need to do this in the ME setup timeframe (usually 2 mins from reboot)

Is there a way that we can re-enable the 16992 or 16993 ports using rpc-go remotely (I have limited physical access to the hosts and even if we could have access to them, they are utilized 99% of the time)?

With that in mind, is there a better way to reconnect hosts that have lost connection to the RPS? Manually connecting to a host and hoping that they have /dev/mei0 running could also prove difficult.

**Comment by graikhel-intel** [comment]
While migrating to the toolkit, did you create a ACM or CCM Profile with CIRA (see steps 11 and 12 in [docs](https://open-amt-cloud-toolkit.github.io/docs/2.21/GetStarted/createProfileACM/#create-a-profile))? If yes, that means AMT is configured to connect to MPS using CIRA and ports 16992/16993 won't be accessible remotely. 

There are 2 ways to connect to AMT, Direct Connect and CIRA
1. Direct connection is recommended for LAN type (flat) networks. In this mode, a console or application can directly talk to AMT using TCP/TLS connection. And Ports 16992/16993 remain open and accessible remotely.
2. CIRA is recommended for Cloud or WAN use cases. In CIRA, all the traffic to AMT can only be routed via MPS, which makes the ports 16992/16993 inaccessible remotely.

Coming back to your question, to enable ports 16992 and 16993, follow these steps:
1. Create a Profile with TLS (see this [doc](https://open-amt-cloud-toolkit.github.io/docs/2.21/Reference/RPS/createProfileTLSConfig/))
2. At step 11, select `Server and Non-TLS Authentication` from the dropdown
3. Run the `rpc-go activate` command on the AMT machine with the new Profile

**Comment by lschnetl** [comment]
Awesome thank you very much! I'll give this a try.

From my understanding, we could only do CIRA from the demo that I followed. But I can take a look at that again to see where I might have missed this part!

**Comment by lschnetl** [comment]
Working! Thank you!
