### ISSUE TITLE
Library build of rpc-go should use return codes

### ISSUE THREAD

**Issue by bgmckown** [open-amt-cloud-toolkit/rpc-go#57]
There are 2 parts to this issue. 

1. When the 'rpcExec' function encounters an error, it will exit via 'os.Exit(1)' or 'log.Fatal(...)' instead of returning an appropriate return/status/error code. This behavior is undesired for library usages of rpc-go as it will cause the parent process to exit instead of gracefully handling the error condition. (Some example of valid error conditions: ME not present, failure to connect to RPS, lack of admin privs, etc.) 

2. The current behavior of the library version of rpc-go also persists the command line usage of reporting everything to stdout. This includes any return/status/error codes and messages. For library usages (instead of command line), it is preferred to have the functions return an appropriate code that can be programmatically acted upon. Currently, we would need to parse the command line output that's provided in order to discern any success/failure conditions, which is less efficient and not ideal. I would like to see the use of return status codes being used instead. 

[AB#14435](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/14435)

**Comment by matt-primrose** [comment]
@bgmckown we're looking at a return code schema that looks something like this:

0: Success
**1-9: Basic errors outside of Open AMT Cloud Toolkit**
1: Incorrect permissions (not admin or sudo)
2: HECI driver not detected
3: AMT not detected
4: AMT not ready
_5-9: Reserved_
**10-19: Input errors to RPC** _we might have to extend this one?_
10: Missing or incorrect URL
11: Missing or incorrect profile
12: Server certificate verification failed
13: Missing or incorrect password
14: Missing DNS Suffix
15: Missing hostname
16: Missing proxy address and port
17: Missing static IP information
_18-19: Reserved_
**20-29: Communication errors**
20: RPS authentication failed
21: AMT authentication failed
22: WSMAN message error
_23-29: Reserved_
**30-99: Activation, configuration, and maintenance status errors**
30: Activation failed
31: Network configuration failed
32: CIRA configuration failed
33: TLS configuration failed
34: WiFi configuration failed
35: AMT features configuration failed
36: 802.1x configuration failed
_37-59: Reserved_
60: Clock sync failed
61: Hostname sync failed
62: Network sync failed
_63-99: Reserved_

**Comment by rsdmike** [comment]
Moved to Github Discussion https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/discussions/146

**Comment by matt-primrose** [comment]
#98 adds return code support for 0-99 based on linked discussion.  Future PR will add support for return codes 100+

**Comment by bwendlandt-intel** [comment]
Completed, [see docs for all return codes](https://open-amt-cloud-toolkit.github.io/docs/2.18/Reference/RPC/libraryRPC/#rpc-error-code-charts)
