### ISSUE TITLE
DNS Suffix .com / .local

### ISSUE THREAD

**Issue by a-feta** [open-amt-cloud-toolkit/rpc-go#615]
Hello!

I have an issue/question regarding the DNS Suffix before purchasing the Certificate from a CA:

If the internal domain is for example xyz.local and the public domain xyz.com, do I have to put the DNS Suffix .local or .com in Option 15 in the DHCP Server?
Normally it's .local but does it work to activate ACM, since the public domain of the webserver ends with .com?

EDIT: If I use the .com DNS Suffix, can I use it temporarily for AMT Setup and change it to .local after?
Also, how do I move to Production? What is the difference from the Sample UI from the Production UI?

Thank you!

**Comment by ctmorris88** [comment]
Hello,

In regard to the certificate you will purchase that supports Intel vPro(R), it needs to reference the "registered" domain, example, xyz.com.     For using DHCP Option 15, you can use either .local or the .com.   

On another note, you can also add the DNS Suffix to the MEBx region for a quick test as well, and it will allow you to perform the ACM utilizing your vPro certificate.

**Comment by bwendlandt-intel** [comment]
In response to:
> Also, how do I move to Production? What is the difference from the Sample UI from the Production UI?

The Sample Web UI is a reference to show how our APIs and UI toolkits can be used to create a cloud-based web console. There is no 'production' version of this UI. The assumption is that developers will either have an existing app/console or are in the process of creating their own app and will integrate our APIs into their solution.

Alternatively, we do have a tool in Beta called Console. This will be a production solution, but it is architected differently. Console is targeted for local network and offers a 'direct connect' solution on a 1:1 basis.

Find more Console details and architecture info here:
https://github.com/open-amt-cloud-toolkit/console
https://open-amt-cloud-toolkit.github.io/docs/2.25/Reference/Console/overview/

**Comment by bwendlandt-intel** [comment]
Closing as answered. Please reopen if you have a follow-on question or comment. Thanks!
