### ISSUE TITLE
RPC-Go not configuring AMT Features from Exported Console Profile

### ISSUE THREAD

**Issue by bwendlandt-intel** [open-amt-cloud-toolkit/rpc-go#680]
AMT Version: 16.1
RPC Version: 2.41.0

Replicate:
1. Create AMT Profile (I used ACM) and Domain Profile with unique AMT features/consent configured.
2. Export profile
3. Try to activate using RPC-Go with profile
4. Device has the default AMT feature configuration, not what was chosen by user

Profile example:
![image](https://github.com/user-attachments/assets/37ef0418-98d5-4211-a615-e43b6cd37f96)

AMT Features after RPC says successful activation:
![image](https://github.com/user-attachments/assets/e74c7107-f57e-45bd-a08b-c70db8d87389)

**Comment by madhavilosetty-intel** [comment]
@bwendlandt-intel it wont configure amtfeatures with an activate command
. Below command is for configuring amt features. 

rpc.exe configure amtfeatures -configv2 <your config file> -configencryptionkey <your key>

Unlike RPS, it doesn't configure everything given in profile/config file. That logic is yet to build and for now, you still need to ask specifically for it.
