### ISSUE TITLE
Latest version of RPC Go 2.42.5 does not work on AMT 11.8

### ISSUE THREAD

**Issue by mtpham-1** [open-amt-cloud-toolkit/rpc-go#717]
When running -local activations in CCM or ACM, it fails with "AMTConnctionFailed" error

![image](https://github.com/user-attachments/assets/7035323b-c72a-4f24-9f8f-377280ce9c9e)

I tried with an old version 2.29.1 and it worked. So there is something in the new version that broke configurations for AMT version 11.8. 

Note: We identified this issue while working with Target on their AMT 11.8 vPro system. . I also reproduced it with my system.

This is also a show stopper for Target so we need to fix this for them to move forward with the migration to OpenAMT Toolkit.

**Comment by graikhel-intel** [comment]
Resolved as part of https://github.com/open-amt-cloud-toolkit/rpc-go/pull/719
